repos:
  # Python hooks
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort

  # TS hooks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier

  # Test hooks
  - repo: local
    hooks:
      - id: run-tests
        name: Run unit tests
        entry: docker-compose exec backend pytest -m unit -vv
        language: system
        pass_filenames: false
