name: CI Pipeline for MR

on:
  push:
    branches:
      - "**"

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install docker-compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and start services
        run: docker-compose up -d --build

      - name: Run integration tests
        run: docker-compose exec -T backend pytest -m unit --disable-warnings -q
