name: CI Pipeline for MR

on:
  push:
    branches:
      - "**"

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install docker-compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and start services
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_SHARED_SECRET: ${{ secrets.LASTFM_SHARED_SECRET }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: docker-compose -f docker-compose.ci.yml up -d --build

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
          if nc -z localhost 3306; then
              echo "MySQL is up!"
              break
          fi
          echo "Waiting for MySQL to start..."
          sleep 2
          done

      - name: Run integration tests
        run: docker-compose exec -T backend pytest -m integration -vv --capture=no || true

      - name: Backend logs
        run: docker-compose logs backend
