# Generated by Django 5.2.3 on 2025-07-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_artist_followers_artist_popularity"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="artists",
            field=models.ManyToManyField(related_name="songs", to="music.artist"),
        ),
        migrations.AlterField(
            model_name="song",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="music.album",
            ),
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("spotify_id", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("cover_url", models.URLField(blank=True)),
                (
                    "songs",
                    models.ManyToManyField(related_name="playlists", to="music.song"),
                ),
            ],
        ),
    ]
