# Generated by Django 5.2.3 on 2025-07-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_song_artists_alter_song_album_playlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="wiki_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="wiki_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="song",
            name="wiki_summary",
            field=models.TextField(blank=True),
        ),
    ]
