# Generated by Django 5.2.4 on 2025-07-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_album_wiki_summary_artist_wiki_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="songs", to="music.genre"
            ),
        ),
    ]
