# Generated by Django 5.2.4 on 2025-07-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0007_mediaitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediaitem",
            name="uploaded_at",
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="height",
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mediaitem",
            name="file",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
