# Generated by Django 5.2.4 on 2025-08-01 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0008_remove_mediaitem_uploaded_at_mediaitem_height_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediaitem",
            name="title",
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="category",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("youtube", "YouTube"),
                ],
                default="Image",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mediaitem",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
