# Generated by Django 5.2.4 on 2025-08-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0009_remove_mediaitem_title_mediaitem_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="bop",
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
