# Generated by Django 5.2.4 on 2025-08-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0010_song_bop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="bop",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
