# Generated by Django 5.2.4 on 2025-08-22 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0011_alter_song_bop"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TMDbGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TMDbList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("anime", "Anime"),
                            ("tv", "TV Show"),
                        ],
                        max_length=10,
                    ),
                ),
                ("last_synced", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TMDbTVMediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.PositiveIntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "episode_run_time",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("first_air_date", models.DateField(blank=True, null=True)),
                ("in_production", models.BooleanField(default=False)),
                ("origin_country", models.CharField(blank=True, max_length=50)),
                ("original_language", models.CharField(blank=True, max_length=10)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("overview", models.TextField(blank=True)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("seasons", models.PositiveIntegerField(default=0)),
                ("vote_average", models.FloatField(default=0)),
                ("vote_count", models.PositiveIntegerField(default=0)),
                ("last_synced", models.DateTimeField(auto_now=True)),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="tv_items", to="music.tmdbgenre"
                    ),
                ),
                (
                    "production_companies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tv_items",
                        to="music.productioncompany",
                    ),
                ),
                (
                    "tmdb_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tv_items",
                        to="music.tmdblist",
                    ),
                ),
            ],
        ),
    ]
