# Generated by Django 5.2.4 on 2025-08-25 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0012_productioncompany_tmdbgenre_tmdblist_tmdbtvmediaitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="TMDbMovieMediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.PositiveIntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("runtime", models.PositiveIntegerField(blank=True, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("origin_country", models.CharField(blank=True, max_length=50)),
                ("original_language", models.CharField(blank=True, max_length=10)),
                ("overview", models.TextField(blank=True)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("vote_average", models.FloatField(default=0)),
                ("vote_count", models.PositiveIntegerField(default=0)),
                ("last_synced", models.DateTimeField(auto_now=True)),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="movie_items", to="music.tmdbgenre"
                    ),
                ),
                (
                    "production_companies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="movie_items",
                        to="music.productioncompany",
                    ),
                ),
                (
                    "tmdb_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_items",
                        to="music.tmdblist",
                    ),
                ),
            ],
        ),
    ]
