# Generated by Django 5.2.4 on 2025-09-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0013_tmdbmoviemediaitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameDeveloper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GamePublisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SteamGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("appID", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                ("release_date", models.CharField(max_length=100)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "developers",
                    models.ManyToManyField(
                        blank=True, related_name="games", to="music.gamedeveloper"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="games", to="music.gamegenre"
                    ),
                ),
                (
                    "publishers",
                    models.ManyToManyField(
                        blank=True, related_name="games", to="music.gamepublisher"
                    ),
                ),
            ],
        ),
    ]
